# Generated by Django 5.1.7 on 2025-03-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('sala_cama', models.CharField(max_length=20)),
                ('dias_hospitalizacion', models.IntegerField(default=0)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('vias_venosas', models.CharField(blank=True, max_length=100, null=True)),
                ('cateter_urinario', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
