# Generated by Django 5.1.7 on 2025-03-13 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario_asociado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
