# Generated by Django 5.1.7 on 2025-03-14 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VIA_VENOSA', 'Vía Venosa'), ('CATETER_URINARIO', 'Catéter Urinario')], max_length=20)),
                ('calibre', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_instalacion', models.DateField()),
                ('dias_instalacion', models.IntegerField(default=1)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_instalacion'],
            },
        ),
    ]
