# Generated by Django 5.1.7 on 2025-03-19 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_edad'),
        ('usuarios', '0005_alter_usuario_anos_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='usuarios.curso'),
        ),
    ]
