# Generated by Django 5.1.7 on 2025-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_remove_paciente_cateter_urinario_and_more'),
        ('usuarios', '0007_fix_invitacion_curso_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('rut', 'curso')},
        ),
    ]
