# Generated by Django 5.1.7 on 2025-03-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_alter_paciente_rut_alter_paciente_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, help_text='Indica las alergias del paciente, separadas por comas', null=True),
        ),
    ]
