# Generated by Django 5.1.7 on 2025-03-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_paciente_alergias'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_alta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
