# Generated by Django 5.1.7 on 2025-04-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_paciente_fecha_alta_paciente_motivo_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alcoholismo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_morbidos',
            field=models.TextField(blank=True, help_text='Antecedentes mórbidos del paciente', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='brazalete',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='paciente',
            name='drogas',
            field=models.CharField(blank=True, help_text='Especifique las drogas', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre'), ('PRAIS', 'Prais'), ('OTRAS', 'Otras')], default='FONASA', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision_otra',
            field=models.CharField(blank=True, help_text='Especifique otra previsión', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tabaquismo',
            field=models.BooleanField(default=False),
        ),
    ]
