# Generated by Django 5.1.7 on 2025-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_paciente_alcoholismo_paciente_antecedentes_morbidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Diagnóstico del paciente', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_consulta',
            field=models.TextField(blank=True, help_text='Motivo de consulta del paciente', null=True),
        ),
    ]
