# Generated by Django 5.1.7 on 2025-04-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_alter_dispositivo_tipo_sonda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo_sonda',
            field=models.CharField(blank=True, choices=[('FOLEY_FR_12', 'Sonda Foley fr 12'), ('FOLEY_FR_14', 'Sonda Foley fr 14'), ('FOLEY_FR_16', 'Sonda Foley fr 16'), ('FOLEY_FR_18', 'Sonda Foley fr 18'), ('FOLEY_FR_20', 'Sonda Foley fr 20'), ('FOLEY_FR_22', 'Sonda Foley fr 22'), ('FOLEY_FR_24', 'Sonda Foley fr 24'), ('FOLEY_FR_26', 'Sonda Foley fr 26'), ('FOLEY_FR_28', 'Sonda Foley fr 28'), ('FOLEY_FR_30', 'Sonda Foley fr 30'), ('NELATON', 'Sonda Nelaton'), ('GASTROSTOMIA', 'Gastrostomía'), ('NASOGASTRICA', 'Sonda Nasogástrica')], max_length=20, null=True),
        ),
    ]
