# Generated by Django 5.1.7 on 2025-04-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0016_alter_dispositivo_tipo_sonda'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='genero_otro',
            field=models.CharField(blank=True, help_text='Especifique otro género', max_length=50, null=True),
        ),
    ]
