# Generated by Django 5.1.7 on 2025-04-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0018_alter_dispositivo_tipo_sonda'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
