# Generated by Django 5.1.7 on 2025-03-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('registro', models.TextField()),
                ('indicaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
