# Generated by Django 5.1.7 on 2025-03-18 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_configuracionusuario_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_dictados', to=settings.AUTH_USER_MODEL)),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='cursos_inscritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo_invitacion', models.CharField(max_length=50, unique=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('aceptada', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='usuarios.curso')),
            ],
            options={
                'verbose_name': 'Invitación a Curso',
                'verbose_name_plural': 'Invitaciones a Cursos',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
