# Generated by Django 5.1.7 on 2025-03-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20250324_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitacioncurso',
            options={'verbose_name': 'Invitación a curso', 'verbose_name_plural': 'Invitaciones a cursos'},
        ),
        migrations.RemoveConstraint(
            model_name='invitacioncurso',
            name='unique_curso_email',
        ),
        migrations.AlterUniqueTogether(
            name='invitacioncurso',
            unique_together={('curso', 'email')},
        ),
    ]
