# Generated by Django 5.1.7 on 2025-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_fix_invitacion_curso_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
