# Generated by Django 5.1.7 on 2025-03-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_fecha_registro_usuario_ultima_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_actividad',
        ),
    ]
