# Generated by Django 5.1.7 on 2025-03-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHidrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.CharField(choices=[('09:00', '09:00'), ('13:00', '13:00'), ('17:00', '17:00'), ('21:00', '21:00'), ('01:00', '01:00'), ('06:00', '06:00')], max_length=5)),
                ('agua', models.IntegerField(default=0)),
                ('soluciones', models.IntegerField(default=0)),
                ('alimentos', models.IntegerField(default=0)),
                ('orina', models.IntegerField(default=0)),
                ('deposiciones', models.CharField(choices=[('+', 'Presente'), ('-', 'Ausente')], default='-', max_length=1)),
                ('vomito', models.CharField(choices=[('+', 'Presente'), ('-', 'Ausente')], default='-', max_length=1)),
            ],
            options={
                'ordering': ['-fecha', 'hora'],
            },
        ),
    ]
