# Generated by Django 5.1.7 on 2025-03-13 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balance_hidrico', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehidrico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_hidricos', to='pacientes.paciente'),
        ),
    ]
