# Generated by Django 5.1.7 on 2025-03-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_hidrico', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehidrico',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancehidrico',
            name='agua',
            field=models.IntegerField(default=0, verbose_name='Agua'),
        ),
        migrations.AlterField(
            model_name='balancehidrico',
            name='alimentos',
            field=models.IntegerField(default=0, verbose_name='Alimentos'),
        ),
        migrations.AlterField(
            model_name='balancehidrico',
            name='deposiciones',
            field=models.IntegerField(default=0, verbose_name='Deposiciones'),
        ),
        migrations.AlterField(
            model_name='balancehidrico',
            name='orina',
            field=models.IntegerField(default=0, verbose_name='Orina'),
        ),
        migrations.AlterField(
            model_name='balancehidrico',
            name='soluciones',
            field=models.IntegerField(default=0, verbose_name='Soluciones'),
        ),
        migrations.AlterField(
            model_name='balancehidrico',
            name='vomito',
            field=models.IntegerField(default=0, verbose_name='Vómito'),
        ),
    ]
