# Generated by Django 5.1.7 on 2025-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_hidrico', '0004_balancehidrico_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehidrico',
            name='deposiciones',
            field=models.CharField(choices=[('+', 'Presente'), ('-', 'Ausente')], default='-', max_length=1, verbose_name='Deposiciones'),
        ),
        migrations.AlterField(
            model_name='balancehidrico',
            name='vomito',
            field=models.CharField(choices=[('+', 'Presente'), ('-', 'Ausente')], default='-', max_length=1, verbose_name='Vómito'),
        ),
    ]
