# Generated by Django 5.1.7 on 2025-04-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_hidrico', '0005_alter_balancehidrico_deposiciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehidrico',
            name='drenaje',
            field=models.IntegerField(default=0, verbose_name='Drenaje'),
        ),
        migrations.AddField(
            model_name='balancehidrico',
            name='hemoderivado',
            field=models.IntegerField(default=0, verbose_name='Hemoderivado'),
        ),
        migrations.AddField(
            model_name='balancehidrico',
            name='medicamentos_sueros',
            field=models.IntegerField(default=0, verbose_name='Medicamentos/Sueros'),
        ),
    ]
