# Generated by Django 5.1.7 on 2025-03-13 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.CharField(choices=[('09:00', '09:00'), ('13:00', '13:00'), ('17:00', '17:00'), ('21:00', '21:00'), ('01:00', '01:00'), ('07:00', '07:00')], max_length=5)),
                ('presion_arterial', models.CharField(max_length=10)),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('saturacion', models.IntegerField()),
                ('fio2', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hgt', models.IntegerField(blank=True, null=True)),
                ('eva', models.IntegerField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-fecha', 'hora'],
            },
        ),
    ]
