# Generated by Django 5.1.7 on 2025-03-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signos_vitales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='estado_hgt',
            field=models.CharField(blank=True, choices=[('ayuno', 'En ayunas'), ('postprandial', 'Post prandial'), ('', 'No especificado')], default='', max_length=15),
        ),
    ]
